project:
  type: website

website:
  title: "HaML Lab"
  google-analytics: "G-BX12VRW5C4"
  cookie-consent: true
  image: images/logo_icon.png
  favicon: images/logo_icon.png
  navbar:
    logo: images/logo_icon.png
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - people.qmd
      - publications.qmd
      - software.qmd
      - positions.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
execute:
  daemon: 10
