project:
  type: website

website:
  title: "HaML Lab"
  google-analytics: "G-BX12VRW5C4"
  cookie-consent: true
  image: images/logo_icon.png
  favicon: images/logo_icon.png
  navbar:
    logo: images/logo_icon.png
    pinned: true
    left:
      - people.qmd
      - publications.qmd
      - software.qmd
      - positions.qmd
    tools:
      - icon: github
        href: "https://github.com/hamllab"
        text: HaML Lab GitHub
  page-footer:
    left: |
      [![](images/UWM_Logo-Preferred_Black-Goldflag.jpg){fig-alt="UWM" width=200px}](https://uwm.edu)
    center: |
      __Contact Us__ <br>
      <br>
      Human and Machine Learning Lab <br>
      Department of Psychology <br>
      University of Wisconsin-Milwaukee <br>
      2441 E Hartford Ave <br>
      Milwaukee, WI 53211
    right: |
      __Affiliations__ <br>
      <br>
      [College of Letters & Science](https://uwm.edu/letters-science/) <br>
      [Psychology Department](https://uwm.edu/psychology/) <br>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
execute:
  daemon: 10
