project:
  type: website

website:
  title: "HaML Lab"
  image: images/logo_icon.png
  navbar:
    logo: images/logo_icon.png
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - people.qmd
      - positions.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
