---
title: "Getting involved"
editor: 
  mode: source
---

# Research Assistant 

## Position Description

The [Human and Machine Learning (HaML) Lab](https://hamllab.org) in the Department of Psychological and Brain Sciences at the University of Wisconsin–Milwaukee is seeking a research assistant. Lab studies will examine how human memory supports optimal decision making in both familiar contexts and new situations, using behavioral and neuroimaging data and model simulations. Lab studies will examine how human memory supports optimal decision making in both familiar contexts and new situations, using behavioral and neuroimaging data and model simulations. This volunteer position that will last for two semesters. This position is ideal for those interested in gaining research experience and the opportunity to present at conferences and co-author publications.

## Background

The HaML Lab studies how humans acquire and apply knowledge to make informed decisions in a complex and uncertain world. We aim to develop a more comprehensive theory of human learning that takes into account memory limitations, motivation, and uncertainty, while explaining how memories are formed and transformed through memory consolidation. We use a combination of behavioral methods from cognitive psychology and neural measures obtained using neuroimaging, which are used to inform development of neurally informed machine learning models that mimic human behavior and brain activity. We ultimately aim to have an impact beyond the lab by informing understanding of memory problems and memory-related disorders such as PTSD. The HaML Lab is directed by [Neal Morton, PhD](people/nealmorton.html). See the [research](https://hamllab.org/research.html) page for more information about Dr. Morton's previous research.

## Roles

To participate in research, undergraduate researchers must first undergo Level I training in one or more of the specific research roles. Level I training involves reading about best practices and passing a short quiz. It's most common to start with being a Study Proctor, who helps run experimental sessions. Researchers can also get involved with designing studies, developing tasks, supervising data collection for a study, or conducting literature reviews.
Undergraduate Researchers can be certified as having completed training for various research roles:
*	Study Designer - Creates the experimental design for a study.
*	Study Developer - Takes an experimental design and implements it as a task.
*	Study Proctor - Runs participants through a task to collect data.
*	Study Coordinator - Supervises data collection for a study and performs quality assurance checks on the data.
Any completed training will be displayed on your profile on the lab website, which you can show to potential employers or graduate school advisors.
After completing Level I training, researchers can work on a project. If they complete a certain amount of research through that project, then they will qualify for Level II certification, which then enables them to take on an independent project like writing a literature review on a topic they're interested in or designing and running a new study. Researchers who complete an independent project and create an approved research product, such as a paper, thesis, or cognitive task, qualify for Level III certification, which indicates that they are skilled at performing some aspect of research independently.


## Benefits

*	Hands-on training in cutting-edge psychology and neuroscience research techniques
*	Experience and training in working with data, data visualization, and science communication
*	Opportunities to present research at national and local conferences, network with leading neuroscientists
*	Professional development for graduate school or research positions
*	A supportive culture that encourages time off and a healthy work-life balance

## Minimum Qualifications
*  Some relevant coursework in psychology, neuroscience, math, and/or statistics

## Preferred Qualifications
*	Experience with research, especially research studies with human participants
*	Programming experience

## How to Apply
To start working as an undergraduate researcher in the lab, contact the Lab Director with relevant information, such as your current transcript and CV/resume, and a short description of why you are interested in doing research in the HaML Lab. Undergraduate researchers can get involved in research as volunteers, for course credit, or for pay through a fellowship program.

# Neuroscience PhD Program

The Human and Machine Learning (HaML) Lab is recruiting a PhD student this year, to start in Fall 2026. If you're interested in human learning, machine learning, and neuroimaging, apply to work with Dr. Neal Morton through UWM's [Neuroscience PhD program](https://uwm.edu/psychology/graduate/phd-program/neuroscience/)! Read on for more specific information about completing a PhD in the [HaML Lab](https://hamllab.org).

## What does the lab do?

* We study how the brain uses cognitive maps to make sense of the world and guide decision making.
* Cognitive maps, which organize structured knowledge, are thought to be critical for learning of the concepts and schemas that help us understand our world.
* We use a combination of model simulations, learning tasks, and neuroimaging to better understand how the brain forms and retrieves information from cognitive maps.
* Our work has implications for understanding human learning, illuminating causes of cognitive disorders, and improving machine learning methods.

You can read [previous publications](/publications.html) from Dr. Morton to get a better sense of the lab's research. 

## What kind of research will PhD students be involved in?

The lab has different focus areas examining behavior, neuroimaging measures, and theoretical work including computational modeling. PhD students can start in any area and learn additional skills from there, and not everyone necessarily has to be involved in every area.

* __Behavioral studies__ examine learning of relationships that are thought to be organized within cognitive maps that help guide flexible reasoning behavior. 
  * Example paper (includes neuroimaging, but behavioral tasks are an important component): [Representations of Temporal Community Structure in Hippocampus and Precuneus Predict Inductive Reasoning Decisions.](https://pubmed.ncbi.nlm.nih.gov/35579986)
  
* __Neuroimaging studies__ are used to examine neural representations of cognitive maps and how these representations relate to behavior. 
  * Example paper: [Representations of common event structure in medial temporal lobe and frontoparietal cortex support efficient inference.](https://pubmed.ncbi.nlm.nih.gov/33229532)
  
* __Theoretical and modeling work__ examines the implications of cognitive map representations within a wide range of behaviors, including memory retrieval, reasoning, and decision making. Longer-term theoretical work will examine potential implications for memory consolidation, dreaming, and PTSD. 
  * Example paper: [Concept formation as a computational cognitive process.](https://pubmed.ncbi.nlm.nih.gov/33628870)

PhD research will generally start by implementing a key study from the lab's planned research program. The student will receive one-on-one guidance in collecting and analyzing data, presenting on the results at a national conference, and publishing in a peer-reviewed journal. After the first major project, the student will work with Dr. Morton to determine a more independent project that will fit with their interests and the lab's research program, while continuing to receive training in critical research skills.

## What experience is helpful as preparation for prospective students?

Research is multifaceted, and all students will receive training in various aspects of research. However, some experience is very helpful before starting a PhD, to start developing research skills and help a prospective student determine whether obtaining a PhD in neuroscience is right for them.

Some experience and skills that are helpful to have:

* Relevant coursework in psychology, neuroscience, math, and statistics
* Experience in conducting psychological studies with humans
* Programming experience with languages such as Python or R
* Knowledge of or experience with neuroimaging

Most important, however, is to have a strong sense of curiosity and the focus and determination needed to answer difficult questions.

## What kind of training do PhD students receive?

In addition to the [graduate courses](https://uwm.edu/psychology/graduate/curriculum-and-courses/) offered through the Psychological and Brain Sciences department, students will receive training through their work in the HaML Lab.

The specific training partially depends on the individual students and their interests; for example, some students may receive significant training and experience in modeling methods, while others may focus more on neuroimaging. However, there are core research skills that all students will receive training on:

* Conducting literature searches
* Designing rigorous tasks for studying human behavior
* Implementing studies using presentation software
* Analyzing behavioral and neuroimaging data
* Code development best practices and software publishing
* Data visualization best practices
* Writing and giving presentations
* Scientific writing
* Grant writing
* Publicizing results to broad audiences

Dr. Morton believes strongly in providing formal training in all areas of research. He will provide documentation and one-on-one training in each of these topics, to ensure that PhD students have the support they need to become capable independent researchers.

## How does the PhD program prepare students for careers in research?

In addition to having frequent meetings about research, students will also regularly meet with Dr. Morton to discuss their larger career goals and the skills, experience, and connections needed to meet those goals. Dr. Morton supports students seeking different career paths and can make use of his connections with academics in many universities and industry connections in software development, data science, machine learning, and bioengineering to help students explore different research-related and technical career paths.

## How can I apply?

See the UWM Psychological & Brain Sciences PHD program website for [instructions on applying](https://uwm.edu/psychology/graduate/application/). Application materials are due on December 1. If you're planning to apply, it's a good idea to contact [Dr. Morton](people/nealmorton.html) first to introduce yourself and say a bit about why you want to work in the lab. It is also helpful to attach a [curriculum vitae](https://www.prospectivedoctor.com/how-to-write-an-undergraduate-cv/). Dr. Morton can answer any questions you have about the program and research in the lab.
